name: cong
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - colorama=0.4.5
  - dataclasses=0.8
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - freetype=2.11.0
  - freetype-py=2.2.0
  - future=0.18.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h5py=3.7.0
  - hdf5=1.10.6
  - imageio=2.19.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - pip=22.1.2
  - pyglet=1.5.11
  - pyrender=0.1.45
  - python=3.9.0
  - python_abi=3.9
  - pyyaml=6.0
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tqdm=4.64.1
  - trimesh=3.14.1
  - tzdata=2022a
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - cycler==0.11.0
    - cython==0.29.32
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - executing==1.0.0
    - fastjsonschema==2.16.1
    - fonttools==4.37.1
    - frozenlist==1.3.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - ipykernel==6.15.2
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.10
    - jsonschema==4.15.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.3
    - jupyter-server==1.18.1
    - jupyter-server-proxy==3.2.2
    - jupyterlab==3.4.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.1
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multidict==6.0.2
    - nbclassic==0.4.3
    - nbclient==0.6.7
    - nbconvert==7.0.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - open3d==0.15.2
    - packaging==21.3
    - pandas==1.4.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.31
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.13.0
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-fcl==0.7.0.1
    - pyzmq==23.2.1
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - send2trash==1.8.0
    - simpervisor==0.4
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomlkit==0.11.4
    - tornado==6.2
    - traitlets==5.3.0
    - urllib3==1.26.12
    - vulture==2.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - widgetsnbextension==4.0.3
    - yarl==1.8.1
    - zipp==3.8.1
